env: "prod"
storage_path: "./storage.db"
http_server:
  address: "0.0.0.0:8082"
  timeout: 4s
  idle_timeout: 30s
  user: "Shabby8574"
client:
  address: "46.161.52.147:44044"
  timeout: 5s
  retries_count: 10